// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sslDebug_Data.proto

#ifndef PROTOBUF_INCLUDED_sslDebug_5fData_2eproto
#define PROTOBUF_INCLUDED_sslDebug_5fData_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_sslDebug_5fData_2eproto 

namespace protobuf_sslDebug_5fData_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_sslDebug_5fData_2eproto
class Debug_AdjustBall;
class Debug_AdjustBallDefaultTypeInternal;
extern Debug_AdjustBallDefaultTypeInternal _Debug_AdjustBall_default_instance_;
class Debug_AdjustBot;
class Debug_AdjustBotDefaultTypeInternal;
extern Debug_AdjustBotDefaultTypeInternal _Debug_AdjustBot_default_instance_;
class Debug_Circle;
class Debug_CircleDefaultTypeInternal;
extern Debug_CircleDefaultTypeInternal _Debug_Circle_default_instance_;
class Debug_Line;
class Debug_LineDefaultTypeInternal;
extern Debug_LineDefaultTypeInternal _Debug_Line_default_instance_;
class sslDebug_Data;
class sslDebug_DataDefaultTypeInternal;
extern sslDebug_DataDefaultTypeInternal _sslDebug_Data_default_instance_;
namespace google {
namespace protobuf {
template<> ::Debug_AdjustBall* Arena::CreateMaybeMessage<::Debug_AdjustBall>(Arena*);
template<> ::Debug_AdjustBot* Arena::CreateMaybeMessage<::Debug_AdjustBot>(Arena*);
template<> ::Debug_Circle* Arena::CreateMaybeMessage<::Debug_Circle>(Arena*);
template<> ::Debug_Line* Arena::CreateMaybeMessage<::Debug_Line>(Arena*);
template<> ::sslDebug_Data* Arena::CreateMaybeMessage<::sslDebug_Data>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class sslDebug_Data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sslDebug_Data) */ {
 public:
  sslDebug_Data();
  virtual ~sslDebug_Data();

  sslDebug_Data(const sslDebug_Data& from);

  inline sslDebug_Data& operator=(const sslDebug_Data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  sslDebug_Data(sslDebug_Data&& from) noexcept
    : sslDebug_Data() {
    *this = ::std::move(from);
  }

  inline sslDebug_Data& operator=(sslDebug_Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const sslDebug_Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const sslDebug_Data* internal_default_instance() {
    return reinterpret_cast<const sslDebug_Data*>(
               &_sslDebug_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(sslDebug_Data* other);
  friend void swap(sslDebug_Data& a, sslDebug_Data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline sslDebug_Data* New() const final {
    return CreateMaybeMessage<sslDebug_Data>(NULL);
  }

  sslDebug_Data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<sslDebug_Data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const sslDebug_Data& from);
  void MergeFrom(const sslDebug_Data& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(sslDebug_Data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Debug_Circle circle = 1;
  int circle_size() const;
  void clear_circle();
  static const int kCircleFieldNumber = 1;
  ::Debug_Circle* mutable_circle(int index);
  ::google::protobuf::RepeatedPtrField< ::Debug_Circle >*
      mutable_circle();
  const ::Debug_Circle& circle(int index) const;
  ::Debug_Circle* add_circle();
  const ::google::protobuf::RepeatedPtrField< ::Debug_Circle >&
      circle() const;

  // repeated .Debug_Line line = 2;
  int line_size() const;
  void clear_line();
  static const int kLineFieldNumber = 2;
  ::Debug_Line* mutable_line(int index);
  ::google::protobuf::RepeatedPtrField< ::Debug_Line >*
      mutable_line();
  const ::Debug_Line& line(int index) const;
  ::Debug_Line* add_line();
  const ::google::protobuf::RepeatedPtrField< ::Debug_Line >&
      line() const;

  // repeated .Debug_AdjustBot botpos = 3;
  int botpos_size() const;
  void clear_botpos();
  static const int kBotposFieldNumber = 3;
  ::Debug_AdjustBot* mutable_botpos(int index);
  ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot >*
      mutable_botpos();
  const ::Debug_AdjustBot& botpos(int index) const;
  ::Debug_AdjustBot* add_botpos();
  const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot >&
      botpos() const;

  // repeated .Debug_AdjustBall ballpos = 4;
  int ballpos_size() const;
  void clear_ballpos();
  static const int kBallposFieldNumber = 4;
  ::Debug_AdjustBall* mutable_ballpos(int index);
  ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall >*
      mutable_ballpos();
  const ::Debug_AdjustBall& ballpos(int index) const;
  ::Debug_AdjustBall* add_ballpos();
  const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall >&
      ballpos() const;

  // @@protoc_insertion_point(class_scope:sslDebug_Data)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Debug_Circle > circle_;
  ::google::protobuf::RepeatedPtrField< ::Debug_Line > line_;
  ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot > botpos_;
  ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall > ballpos_;
  friend struct ::protobuf_sslDebug_5fData_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug_Circle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Debug_Circle) */ {
 public:
  Debug_Circle();
  virtual ~Debug_Circle();

  Debug_Circle(const Debug_Circle& from);

  inline Debug_Circle& operator=(const Debug_Circle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug_Circle(Debug_Circle&& from) noexcept
    : Debug_Circle() {
    *this = ::std::move(from);
  }

  inline Debug_Circle& operator=(Debug_Circle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug_Circle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug_Circle* internal_default_instance() {
    return reinterpret_cast<const Debug_Circle*>(
               &_Debug_Circle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Debug_Circle* other);
  friend void swap(Debug_Circle& a, Debug_Circle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug_Circle* New() const final {
    return CreateMaybeMessage<Debug_Circle>(NULL);
  }

  Debug_Circle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug_Circle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug_Circle& from);
  void MergeFrom(const Debug_Circle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug_Circle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // required uint32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // required uint32 radius = 3;
  bool has_radius() const;
  void clear_radius();
  static const int kRadiusFieldNumber = 3;
  ::google::protobuf::uint32 radius() const;
  void set_radius(::google::protobuf::uint32 value);

  // required uint32 color = 4;
  bool has_color() const;
  void clear_color();
  static const int kColorFieldNumber = 4;
  ::google::protobuf::uint32 color() const;
  void set_color(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Debug_Circle)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_radius();
  void clear_has_radius();
  void set_has_color();
  void clear_has_color();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  ::google::protobuf::uint32 radius_;
  ::google::protobuf::uint32 color_;
  friend struct ::protobuf_sslDebug_5fData_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug_Line : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Debug_Line) */ {
 public:
  Debug_Line();
  virtual ~Debug_Line();

  Debug_Line(const Debug_Line& from);

  inline Debug_Line& operator=(const Debug_Line& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug_Line(Debug_Line&& from) noexcept
    : Debug_Line() {
    *this = ::std::move(from);
  }

  inline Debug_Line& operator=(Debug_Line&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug_Line& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug_Line* internal_default_instance() {
    return reinterpret_cast<const Debug_Line*>(
               &_Debug_Line_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Debug_Line* other);
  friend void swap(Debug_Line& a, Debug_Line& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug_Line* New() const final {
    return CreateMaybeMessage<Debug_Line>(NULL);
  }

  Debug_Line* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug_Line>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug_Line& from);
  void MergeFrom(const Debug_Line& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug_Line* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 x1 = 1;
  bool has_x1() const;
  void clear_x1();
  static const int kX1FieldNumber = 1;
  ::google::protobuf::uint32 x1() const;
  void set_x1(::google::protobuf::uint32 value);

  // required uint32 y1 = 2;
  bool has_y1() const;
  void clear_y1();
  static const int kY1FieldNumber = 2;
  ::google::protobuf::uint32 y1() const;
  void set_y1(::google::protobuf::uint32 value);

  // required uint32 x2 = 3;
  bool has_x2() const;
  void clear_x2();
  static const int kX2FieldNumber = 3;
  ::google::protobuf::uint32 x2() const;
  void set_x2(::google::protobuf::uint32 value);

  // required uint32 y2 = 4;
  bool has_y2() const;
  void clear_y2();
  static const int kY2FieldNumber = 4;
  ::google::protobuf::uint32 y2() const;
  void set_y2(::google::protobuf::uint32 value);

  // required uint32 color = 5;
  bool has_color() const;
  void clear_color();
  static const int kColorFieldNumber = 5;
  ::google::protobuf::uint32 color() const;
  void set_color(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Debug_Line)
 private:
  void set_has_x1();
  void clear_has_x1();
  void set_has_y1();
  void clear_has_y1();
  void set_has_x2();
  void clear_has_x2();
  void set_has_y2();
  void clear_has_y2();
  void set_has_color();
  void clear_has_color();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 x1_;
  ::google::protobuf::uint32 y1_;
  ::google::protobuf::uint32 x2_;
  ::google::protobuf::uint32 y2_;
  ::google::protobuf::uint32 color_;
  friend struct ::protobuf_sslDebug_5fData_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug_AdjustBot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Debug_AdjustBot) */ {
 public:
  Debug_AdjustBot();
  virtual ~Debug_AdjustBot();

  Debug_AdjustBot(const Debug_AdjustBot& from);

  inline Debug_AdjustBot& operator=(const Debug_AdjustBot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug_AdjustBot(Debug_AdjustBot&& from) noexcept
    : Debug_AdjustBot() {
    *this = ::std::move(from);
  }

  inline Debug_AdjustBot& operator=(Debug_AdjustBot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug_AdjustBot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug_AdjustBot* internal_default_instance() {
    return reinterpret_cast<const Debug_AdjustBot*>(
               &_Debug_AdjustBot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Debug_AdjustBot* other);
  friend void swap(Debug_AdjustBot& a, Debug_AdjustBot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug_AdjustBot* New() const final {
    return CreateMaybeMessage<Debug_AdjustBot>(NULL);
  }

  Debug_AdjustBot* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug_AdjustBot>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug_AdjustBot& from);
  void MergeFrom(const Debug_AdjustBot& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug_AdjustBot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // required float dir = 4;
  bool has_dir() const;
  void clear_dir();
  static const int kDirFieldNumber = 4;
  float dir() const;
  void set_dir(float value);

  // required int32 vx = 5;
  bool has_vx() const;
  void clear_vx();
  static const int kVxFieldNumber = 5;
  ::google::protobuf::int32 vx() const;
  void set_vx(::google::protobuf::int32 value);

  // required int32 vy = 6;
  bool has_vy() const;
  void clear_vy();
  static const int kVyFieldNumber = 6;
  ::google::protobuf::int32 vy() const;
  void set_vy(::google::protobuf::int32 value);

  // required int32 vz = 7;
  bool has_vz() const;
  void clear_vz();
  static const int kVzFieldNumber = 7;
  ::google::protobuf::int32 vz() const;
  void set_vz(::google::protobuf::int32 value);

  // required uint32 team = 8;
  bool has_team() const;
  void clear_team();
  static const int kTeamFieldNumber = 8;
  ::google::protobuf::uint32 team() const;
  void set_team(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Debug_AdjustBot)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_dir();
  void clear_has_dir();
  void set_has_vx();
  void clear_has_vx();
  void set_has_vy();
  void clear_has_vy();
  void set_has_vz();
  void clear_has_vz();
  void set_has_team();
  void clear_has_team();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  float dir_;
  ::google::protobuf::int32 vx_;
  ::google::protobuf::int32 vy_;
  ::google::protobuf::int32 vz_;
  ::google::protobuf::uint32 team_;
  friend struct ::protobuf_sslDebug_5fData_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug_AdjustBall : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Debug_AdjustBall) */ {
 public:
  Debug_AdjustBall();
  virtual ~Debug_AdjustBall();

  Debug_AdjustBall(const Debug_AdjustBall& from);

  inline Debug_AdjustBall& operator=(const Debug_AdjustBall& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug_AdjustBall(Debug_AdjustBall&& from) noexcept
    : Debug_AdjustBall() {
    *this = ::std::move(from);
  }

  inline Debug_AdjustBall& operator=(Debug_AdjustBall&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug_AdjustBall& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug_AdjustBall* internal_default_instance() {
    return reinterpret_cast<const Debug_AdjustBall*>(
               &_Debug_AdjustBall_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Debug_AdjustBall* other);
  friend void swap(Debug_AdjustBall& a, Debug_AdjustBall& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug_AdjustBall* New() const final {
    return CreateMaybeMessage<Debug_AdjustBall>(NULL);
  }

  Debug_AdjustBall* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug_AdjustBall>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug_AdjustBall& from);
  void MergeFrom(const Debug_AdjustBall& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug_AdjustBall* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // required int32 vx = 3;
  bool has_vx() const;
  void clear_vx();
  static const int kVxFieldNumber = 3;
  ::google::protobuf::int32 vx() const;
  void set_vx(::google::protobuf::int32 value);

  // required int32 vy = 4;
  bool has_vy() const;
  void clear_vy();
  static const int kVyFieldNumber = 4;
  ::google::protobuf::int32 vy() const;
  void set_vy(::google::protobuf::int32 value);

  // required int32 vz = 5;
  bool has_vz() const;
  void clear_vz();
  static const int kVzFieldNumber = 5;
  ::google::protobuf::int32 vz() const;
  void set_vz(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Debug_AdjustBall)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_vx();
  void clear_has_vx();
  void set_has_vy();
  void clear_has_vy();
  void set_has_vz();
  void clear_has_vz();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 vx_;
  ::google::protobuf::int32 vy_;
  ::google::protobuf::int32 vz_;
  friend struct ::protobuf_sslDebug_5fData_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// sslDebug_Data

// repeated .Debug_Circle circle = 1;
inline int sslDebug_Data::circle_size() const {
  return circle_.size();
}
inline void sslDebug_Data::clear_circle() {
  circle_.Clear();
}
inline ::Debug_Circle* sslDebug_Data::mutable_circle(int index) {
  // @@protoc_insertion_point(field_mutable:sslDebug_Data.circle)
  return circle_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Debug_Circle >*
sslDebug_Data::mutable_circle() {
  // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.circle)
  return &circle_;
}
inline const ::Debug_Circle& sslDebug_Data::circle(int index) const {
  // @@protoc_insertion_point(field_get:sslDebug_Data.circle)
  return circle_.Get(index);
}
inline ::Debug_Circle* sslDebug_Data::add_circle() {
  // @@protoc_insertion_point(field_add:sslDebug_Data.circle)
  return circle_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Debug_Circle >&
sslDebug_Data::circle() const {
  // @@protoc_insertion_point(field_list:sslDebug_Data.circle)
  return circle_;
}

// repeated .Debug_Line line = 2;
inline int sslDebug_Data::line_size() const {
  return line_.size();
}
inline void sslDebug_Data::clear_line() {
  line_.Clear();
}
inline ::Debug_Line* sslDebug_Data::mutable_line(int index) {
  // @@protoc_insertion_point(field_mutable:sslDebug_Data.line)
  return line_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Debug_Line >*
sslDebug_Data::mutable_line() {
  // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.line)
  return &line_;
}
inline const ::Debug_Line& sslDebug_Data::line(int index) const {
  // @@protoc_insertion_point(field_get:sslDebug_Data.line)
  return line_.Get(index);
}
inline ::Debug_Line* sslDebug_Data::add_line() {
  // @@protoc_insertion_point(field_add:sslDebug_Data.line)
  return line_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Debug_Line >&
sslDebug_Data::line() const {
  // @@protoc_insertion_point(field_list:sslDebug_Data.line)
  return line_;
}

// repeated .Debug_AdjustBot botpos = 3;
inline int sslDebug_Data::botpos_size() const {
  return botpos_.size();
}
inline void sslDebug_Data::clear_botpos() {
  botpos_.Clear();
}
inline ::Debug_AdjustBot* sslDebug_Data::mutable_botpos(int index) {
  // @@protoc_insertion_point(field_mutable:sslDebug_Data.botpos)
  return botpos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot >*
sslDebug_Data::mutable_botpos() {
  // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.botpos)
  return &botpos_;
}
inline const ::Debug_AdjustBot& sslDebug_Data::botpos(int index) const {
  // @@protoc_insertion_point(field_get:sslDebug_Data.botpos)
  return botpos_.Get(index);
}
inline ::Debug_AdjustBot* sslDebug_Data::add_botpos() {
  // @@protoc_insertion_point(field_add:sslDebug_Data.botpos)
  return botpos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBot >&
sslDebug_Data::botpos() const {
  // @@protoc_insertion_point(field_list:sslDebug_Data.botpos)
  return botpos_;
}

// repeated .Debug_AdjustBall ballpos = 4;
inline int sslDebug_Data::ballpos_size() const {
  return ballpos_.size();
}
inline void sslDebug_Data::clear_ballpos() {
  ballpos_.Clear();
}
inline ::Debug_AdjustBall* sslDebug_Data::mutable_ballpos(int index) {
  // @@protoc_insertion_point(field_mutable:sslDebug_Data.ballpos)
  return ballpos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall >*
sslDebug_Data::mutable_ballpos() {
  // @@protoc_insertion_point(field_mutable_list:sslDebug_Data.ballpos)
  return &ballpos_;
}
inline const ::Debug_AdjustBall& sslDebug_Data::ballpos(int index) const {
  // @@protoc_insertion_point(field_get:sslDebug_Data.ballpos)
  return ballpos_.Get(index);
}
inline ::Debug_AdjustBall* sslDebug_Data::add_ballpos() {
  // @@protoc_insertion_point(field_add:sslDebug_Data.ballpos)
  return ballpos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Debug_AdjustBall >&
sslDebug_Data::ballpos() const {
  // @@protoc_insertion_point(field_list:sslDebug_Data.ballpos)
  return ballpos_;
}

// -------------------------------------------------------------------

// Debug_Circle

// required uint32 x = 1;
inline bool Debug_Circle::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Debug_Circle::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Debug_Circle::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Debug_Circle::clear_x() {
  x_ = 0u;
  clear_has_x();
}
inline ::google::protobuf::uint32 Debug_Circle::x() const {
  // @@protoc_insertion_point(field_get:Debug_Circle.x)
  return x_;
}
inline void Debug_Circle::set_x(::google::protobuf::uint32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Debug_Circle.x)
}

// required uint32 y = 2;
inline bool Debug_Circle::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Debug_Circle::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Debug_Circle::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Debug_Circle::clear_y() {
  y_ = 0u;
  clear_has_y();
}
inline ::google::protobuf::uint32 Debug_Circle::y() const {
  // @@protoc_insertion_point(field_get:Debug_Circle.y)
  return y_;
}
inline void Debug_Circle::set_y(::google::protobuf::uint32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Debug_Circle.y)
}

// required uint32 radius = 3;
inline bool Debug_Circle::has_radius() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Debug_Circle::set_has_radius() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Debug_Circle::clear_has_radius() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Debug_Circle::clear_radius() {
  radius_ = 0u;
  clear_has_radius();
}
inline ::google::protobuf::uint32 Debug_Circle::radius() const {
  // @@protoc_insertion_point(field_get:Debug_Circle.radius)
  return radius_;
}
inline void Debug_Circle::set_radius(::google::protobuf::uint32 value) {
  set_has_radius();
  radius_ = value;
  // @@protoc_insertion_point(field_set:Debug_Circle.radius)
}

// required uint32 color = 4;
inline bool Debug_Circle::has_color() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Debug_Circle::set_has_color() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Debug_Circle::clear_has_color() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Debug_Circle::clear_color() {
  color_ = 0u;
  clear_has_color();
}
inline ::google::protobuf::uint32 Debug_Circle::color() const {
  // @@protoc_insertion_point(field_get:Debug_Circle.color)
  return color_;
}
inline void Debug_Circle::set_color(::google::protobuf::uint32 value) {
  set_has_color();
  color_ = value;
  // @@protoc_insertion_point(field_set:Debug_Circle.color)
}

// -------------------------------------------------------------------

// Debug_Line

// required uint32 x1 = 1;
inline bool Debug_Line::has_x1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Debug_Line::set_has_x1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Debug_Line::clear_has_x1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Debug_Line::clear_x1() {
  x1_ = 0u;
  clear_has_x1();
}
inline ::google::protobuf::uint32 Debug_Line::x1() const {
  // @@protoc_insertion_point(field_get:Debug_Line.x1)
  return x1_;
}
inline void Debug_Line::set_x1(::google::protobuf::uint32 value) {
  set_has_x1();
  x1_ = value;
  // @@protoc_insertion_point(field_set:Debug_Line.x1)
}

// required uint32 y1 = 2;
inline bool Debug_Line::has_y1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Debug_Line::set_has_y1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Debug_Line::clear_has_y1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Debug_Line::clear_y1() {
  y1_ = 0u;
  clear_has_y1();
}
inline ::google::protobuf::uint32 Debug_Line::y1() const {
  // @@protoc_insertion_point(field_get:Debug_Line.y1)
  return y1_;
}
inline void Debug_Line::set_y1(::google::protobuf::uint32 value) {
  set_has_y1();
  y1_ = value;
  // @@protoc_insertion_point(field_set:Debug_Line.y1)
}

// required uint32 x2 = 3;
inline bool Debug_Line::has_x2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Debug_Line::set_has_x2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Debug_Line::clear_has_x2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Debug_Line::clear_x2() {
  x2_ = 0u;
  clear_has_x2();
}
inline ::google::protobuf::uint32 Debug_Line::x2() const {
  // @@protoc_insertion_point(field_get:Debug_Line.x2)
  return x2_;
}
inline void Debug_Line::set_x2(::google::protobuf::uint32 value) {
  set_has_x2();
  x2_ = value;
  // @@protoc_insertion_point(field_set:Debug_Line.x2)
}

// required uint32 y2 = 4;
inline bool Debug_Line::has_y2() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Debug_Line::set_has_y2() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Debug_Line::clear_has_y2() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Debug_Line::clear_y2() {
  y2_ = 0u;
  clear_has_y2();
}
inline ::google::protobuf::uint32 Debug_Line::y2() const {
  // @@protoc_insertion_point(field_get:Debug_Line.y2)
  return y2_;
}
inline void Debug_Line::set_y2(::google::protobuf::uint32 value) {
  set_has_y2();
  y2_ = value;
  // @@protoc_insertion_point(field_set:Debug_Line.y2)
}

// required uint32 color = 5;
inline bool Debug_Line::has_color() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Debug_Line::set_has_color() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Debug_Line::clear_has_color() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Debug_Line::clear_color() {
  color_ = 0u;
  clear_has_color();
}
inline ::google::protobuf::uint32 Debug_Line::color() const {
  // @@protoc_insertion_point(field_get:Debug_Line.color)
  return color_;
}
inline void Debug_Line::set_color(::google::protobuf::uint32 value) {
  set_has_color();
  color_ = value;
  // @@protoc_insertion_point(field_set:Debug_Line.color)
}

// -------------------------------------------------------------------

// Debug_AdjustBot

// required uint32 id = 1;
inline bool Debug_AdjustBot::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Debug_AdjustBot::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Debug_AdjustBot::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Debug_AdjustBot::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Debug_AdjustBot::id() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.id)
  return id_;
}
inline void Debug_AdjustBot::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.id)
}

// required int32 x = 2;
inline bool Debug_AdjustBot::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Debug_AdjustBot::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Debug_AdjustBot::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Debug_AdjustBot::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Debug_AdjustBot::x() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.x)
  return x_;
}
inline void Debug_AdjustBot::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.x)
}

// required int32 y = 3;
inline bool Debug_AdjustBot::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Debug_AdjustBot::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Debug_AdjustBot::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Debug_AdjustBot::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Debug_AdjustBot::y() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.y)
  return y_;
}
inline void Debug_AdjustBot::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.y)
}

// required float dir = 4;
inline bool Debug_AdjustBot::has_dir() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Debug_AdjustBot::set_has_dir() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Debug_AdjustBot::clear_has_dir() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Debug_AdjustBot::clear_dir() {
  dir_ = 0;
  clear_has_dir();
}
inline float Debug_AdjustBot::dir() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.dir)
  return dir_;
}
inline void Debug_AdjustBot::set_dir(float value) {
  set_has_dir();
  dir_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.dir)
}

// required int32 vx = 5;
inline bool Debug_AdjustBot::has_vx() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Debug_AdjustBot::set_has_vx() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Debug_AdjustBot::clear_has_vx() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Debug_AdjustBot::clear_vx() {
  vx_ = 0;
  clear_has_vx();
}
inline ::google::protobuf::int32 Debug_AdjustBot::vx() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.vx)
  return vx_;
}
inline void Debug_AdjustBot::set_vx(::google::protobuf::int32 value) {
  set_has_vx();
  vx_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.vx)
}

// required int32 vy = 6;
inline bool Debug_AdjustBot::has_vy() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Debug_AdjustBot::set_has_vy() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Debug_AdjustBot::clear_has_vy() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Debug_AdjustBot::clear_vy() {
  vy_ = 0;
  clear_has_vy();
}
inline ::google::protobuf::int32 Debug_AdjustBot::vy() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.vy)
  return vy_;
}
inline void Debug_AdjustBot::set_vy(::google::protobuf::int32 value) {
  set_has_vy();
  vy_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.vy)
}

// required int32 vz = 7;
inline bool Debug_AdjustBot::has_vz() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Debug_AdjustBot::set_has_vz() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Debug_AdjustBot::clear_has_vz() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Debug_AdjustBot::clear_vz() {
  vz_ = 0;
  clear_has_vz();
}
inline ::google::protobuf::int32 Debug_AdjustBot::vz() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.vz)
  return vz_;
}
inline void Debug_AdjustBot::set_vz(::google::protobuf::int32 value) {
  set_has_vz();
  vz_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.vz)
}

// required uint32 team = 8;
inline bool Debug_AdjustBot::has_team() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Debug_AdjustBot::set_has_team() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Debug_AdjustBot::clear_has_team() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Debug_AdjustBot::clear_team() {
  team_ = 0u;
  clear_has_team();
}
inline ::google::protobuf::uint32 Debug_AdjustBot::team() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBot.team)
  return team_;
}
inline void Debug_AdjustBot::set_team(::google::protobuf::uint32 value) {
  set_has_team();
  team_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBot.team)
}

// -------------------------------------------------------------------

// Debug_AdjustBall

// required int32 x = 1;
inline bool Debug_AdjustBall::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Debug_AdjustBall::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Debug_AdjustBall::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Debug_AdjustBall::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Debug_AdjustBall::x() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBall.x)
  return x_;
}
inline void Debug_AdjustBall::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBall.x)
}

// required int32 y = 2;
inline bool Debug_AdjustBall::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Debug_AdjustBall::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Debug_AdjustBall::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Debug_AdjustBall::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Debug_AdjustBall::y() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBall.y)
  return y_;
}
inline void Debug_AdjustBall::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBall.y)
}

// required int32 vx = 3;
inline bool Debug_AdjustBall::has_vx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Debug_AdjustBall::set_has_vx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Debug_AdjustBall::clear_has_vx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Debug_AdjustBall::clear_vx() {
  vx_ = 0;
  clear_has_vx();
}
inline ::google::protobuf::int32 Debug_AdjustBall::vx() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBall.vx)
  return vx_;
}
inline void Debug_AdjustBall::set_vx(::google::protobuf::int32 value) {
  set_has_vx();
  vx_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBall.vx)
}

// required int32 vy = 4;
inline bool Debug_AdjustBall::has_vy() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Debug_AdjustBall::set_has_vy() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Debug_AdjustBall::clear_has_vy() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Debug_AdjustBall::clear_vy() {
  vy_ = 0;
  clear_has_vy();
}
inline ::google::protobuf::int32 Debug_AdjustBall::vy() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBall.vy)
  return vy_;
}
inline void Debug_AdjustBall::set_vy(::google::protobuf::int32 value) {
  set_has_vy();
  vy_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBall.vy)
}

// required int32 vz = 5;
inline bool Debug_AdjustBall::has_vz() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Debug_AdjustBall::set_has_vz() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Debug_AdjustBall::clear_has_vz() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Debug_AdjustBall::clear_vz() {
  vz_ = 0;
  clear_has_vz();
}
inline ::google::protobuf::int32 Debug_AdjustBall::vz() const {
  // @@protoc_insertion_point(field_get:Debug_AdjustBall.vz)
  return vz_;
}
inline void Debug_AdjustBall::set_vz(::google::protobuf::int32 value) {
  set_has_vz();
  vz_ = value;
  // @@protoc_insertion_point(field_set:Debug_AdjustBall.vz)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_sslDebug_5fData_2eproto
