#include "tactic.h"
#include "tAttack.hpp"
#include "tAttack2015.hpp"
#include "tAttackSpline.hpp"
#include "tSupportAttack2015.hpp"
#include "tBlock.hpp"
#include "tCharge.hpp"
#include "tDefend.hpp"
#include "tDefendLine.hpp"
#include "tDefendPoint.hpp"
#include "tGoalKeepingOurSide.hpp"
#include "tPass.hpp"
#include "tPosition.hpp"
#include "tReceiveBall.hpp"
#include "tReceiveSpline.hpp"
#include "tShoot.hpp"
#include "tStop.hpp"
#include "tVelocity.hpp"
#include "tCoverGoal.hpp"
#include "tGoalKick.hpp"
#include "tDefender2.hpp"
#include "tDWDefender2015.hpp"
#include "tCoverGoal2015.hpp"
#include "tCoverGoalPairLeft.hpp"
#include "tCoverGoalPairRight.hpp"
#include "tGoalie2.hpp"
#include "tReceiveBall2015.hpp"

//#include "tDragToGoal.hpp"
#include "tBackup.hpp"
#include "TestgoToPoint.hpp"
#include "Testbotrace.hpp"
#include "tKickoff.hpp"

//two bot tactics
#include "tactic2.h"
//#include "tAttackDuo.hpp"